In [113]:
import numpy as np

In [114]:
sudoku = np.array([
    [5, 3, 4, 6, 7, 8, 9, 1, 2],
    [6, 7, 2, 1, 9, 5, 3, 4, 8],
    [1, 9, 8, 3, 4, 2, 5, 6, 7],
    [8, 5, 9, 7, 6, 1, 4, 2, 3],
    [4, 2, 6, 8, 5, 3, 7, 9, 1],
    [7, 1, 3, 9, 2, 4, 8, 5, 6],
    [9, 6, 1, 5, 3, 7, 2, 8, 4],
    [2, 8, 7, 4, 1, 9, 6, 3, 5],
    [3, 4, 5, 2, 8, 6, 1, 7, 9]
])

print(sudoku.shape)
print(sudoku.ndim)
print(sudoku.dtype)

In [115]:
print(sudoku)

[[5 3 4 6 7 8 9 1 2]
 [6 7 2 1 9 5 3 4 8]
 [1 9 8 3 4 2 5 6 7]
 [8 5 9 7 6 1 4 2 3]
 [4 2 6 8 5 3 7 9 1]
 [7 1 3 9 2 4 8 5 6]
 [9 6 1 5 3 7 2 8 4]
 [2 8 7 4 1 9 6 3 5]
 [3 4 5 2 8 6 1 7 9]]


In [116]:
print(sudoku.shape)
print(sudoku.ndim)
print(sudoku.dtype)

(9, 9)
2
int64


In [117]:
print(np.sum(sudoku))

405


In [118]:
print(np.sum(sudoku,axis=1))

[45 45 45 45 45 45 45 45 45]


In [119]:
row =np.sum(sudoku,axis=1)
print(row)

[45 45 45 45 45 45 45 45 45]


In [120]:
column = np.sum(sudoku,axis=0)
print(column)

[45 45 45 45 45 45 45 45 45]


In [121]:
print(row==45)
print(column==45)

[ True  True  True  True  True  True  True  True  True]
[ True  True  True  True  True  True  True  True  True]


In [122]:
print(sudoku[0:3,0:3])

[[5 3 4]
 [6 7 2]
 [1 9 8]]


In [123]:
block1 = np.sum(sudoku[0:3,0:3],axis=0)
print(block)

[12 19 14]


In [124]:


print(sudoku[0:3,3:6])

[[6 7 8]
 [1 9 5]
 [3 4 2]]


In [125]:
block2= np.su
m(sudoku[0:3,3:6],axis=0)
print(block2)

AttributeError: module 'numpy' has no attribute 'su'

In [ ]:
print(sudoku[6:9,6:9])

[[2 8 4]
 [6 3 5]
 [1 7 9]]


In [ ]:
data = np.array([
    [18,85,75],
    [19,95,79],
    [17,75,90],
    [18,85,96],
    [19,99,78],
    [18,90,80]
    
])
print(data)

[[18 85 75]
 [19 95 79]
 [17 75 90]
 [18 85 96]
 [19 99 78]
 [18 90 80]]


In [ ]:
#shape of matrix
print(data.shape)

(6, 3)


In [ ]:
#print avg age of student

avg = np.mean((data[:,:1]))
print(avg)

18.166666666666668


In [ ]:
#print all student math mark
print(data[:,1])

[85 95 75 85 78 90]


In [ ]:
#find highest score science mask
high =np.max(data[:,2])
print(high)


96


In [ ]:
#get student detail who score more than 90
more_90=data[:,1]>90
print(data[more_90])

[[19 95 79]
 [19 99 78]]


In [ ]:
# increse mark by +5
app =np.append(data[:,1],5)
print(app)

[85 95 75 85 99 90  5]


In [ ]:
#or add +5 
data[:,2]+5


array([ 80,  84,  74, 101,  83,  85])

In [ ]:
#student younger than 19 or  less than 19
y=data[:,0]<19
print(data[y])
print(len(data[y]))


[[18 85 75]
 [17 75 69]
 [18 85 96]
 [18 90 80]]
4


In [127]:
#calculate avg mark in math and each subject

avg1 = np.mean(data[:,1:],axis=0)
print(avg1)

[88.16666667 83.        ]


In [149]:
# find student who scored at least 80 mark in both subject

c =np.where((data[:,1]>80) & (data[:,2]>80))
print(data[c])


[[18 85 96]]


In [143]:
rows = np.all(data[:, 1:] > 80, axis=1)
print(data[rows])


[[18 85 96]]


In [160]:
arr = np.array([1,5,8,9,-8],dtype=float)
print(arr)
arr[::-1]

[ 1.  5.  8.  9. -8.]


array([-8.,  9.,  8.,  5.,  1.])